apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-cdn-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
data:
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_DB: "${REDIS_DB}"
  MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
  MINIO_REGION: "${MINIO_REGION}"
  MINIO_USE_SSL: "${MINIO_USE_SSL}"
  CACHE_TIME: "${CACHE_TIME}"
  DOMAIN_NAME: "${DOMAIN_NAME}"
  GRAFANA_OTLP_ENDPOINT: "${GRAFANA_OTLP_ENDPOINT}"
  SERVICE_NAME: "${SERVICE_NAME}"
  DEPLOY_ENV: "${DEPLOY_ENV}"
  GROUP_NAME: "${GROUP_NAME}"
