apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-cdn-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
data:
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PORT: "${REDIS_PORT}"
  REDIS_DB: "${REDIS_DB}"
  CACHE_TIME: "${CACHE_TIME}"
  CACHE_SIZE: "${CACHE_SIZE}"
  GRAFANA_OTLP_ENDPOINT: "${GRAFANA_OTLP_ENDPOINT}"
  SERVICE_NAME: "${SERVICE_NAME}"
  DEPLOY_ENV: "${DEPLOY_ENV}"
  GROUP_NAME: "${GROUP_NAME}"
