apiVersion: v1
kind: Secret
metadata:
  name: gau-cdn-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
type: Opaque
stringData:
  MINIO_ACCESS_KEY_ID: "${MINIO_ACCESS_KEY_ID}"
  MINIO_SECRET_ACCESS_KEY: "${MINIO_SECRET_ACCESS_KEY}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
