apiVersion: v1
kind: Service
metadata:
  name: gau-cdn-http-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: gau-cdn-http-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cdn-service
  namespace: bao-${DEPLOY_ENV}-env
spec:
  selector:
    app: redis-cdn-service
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP